### ISSUE TITLE
Mirror the template for left-handed people

### ISSUE THREAD

**Issue by isman7** [dynobo/noteto#53]
Hi! I came directly here from reddit, it seems you like have issues to have backlog. So, adding a mirror template would be nice, mine looks like this: 

![image](https://user-images.githubusercontent.com/9478220/111391385-d1619280-86b4-11eb-9a16-3afcc483f1aa.png)

**Comment by dynobo** [comment]
fixed by 7c6c62f6b21619d2516949bff97d462cc1cce7eb
