### ISSUE TITLE
Serve from the remarkable and create service to save the templates

### ISSUE THREAD

**Issue by isman7** [dynobo/noteto#54]
Is this too much? And also might be outside the scope of your project, but I've been playing to run Python inside the rm2 for a week. The setup is a bit pain in the ass, but is quite possible. So, maybe having a little service with bottle framework to serve NoTeTo (GET) and save the templates into the remarkable (POST). Some pics: 

![image](https://user-images.githubusercontent.com/9478220/111393950-06bcaf00-86ba-11eb-99b7-7217f8c0a060.png)

![image](https://user-images.githubusercontent.com/9478220/111393981-1805bb80-86ba-11eb-9a79-c4bcfb89d51b.png)

**Comment by dynobo** [comment]
Hi @isman7,

thanks for your feature request, but yes, unfortunately this is too much for this project. I especially want to avoid the hassle to operate any backend. 

However, if someone else would provide and operate a proper backend, I certainly would be open to collaborate for an integration!

**Comment by isman7** [comment]
I still need to further learn more about the remarkable and its possibilities, to make a serious attempt to do so. Another possibility here is to hack a little bit the web interface of the remarkable to allocate your project. I would like the idea to ship it with remarkable everywhere, still would lack the backend, though. 

Happy to ask for help for future integrations if the time comes.

Cheers,

Ismael
