### ISSUE TITLE
Add description of what parts of file names are

### ISSUE THREAD

**Issue by Bootstrap360** [dynobo/noteto#66]
Hello Dynobo,

Thank you for your work and the releases here: https://github.com/kudrykv/latex-yearly-planner/releases/tag/v0.0.8

Could you please add a table in the readme of what all the pieces of the file names are?

For example

| Name Component | Definition |
| -- | -- | 
| Breadcrum | Navigation bar at the top of daily page is a bread crumb of where the pages is |
| dotted | Notes on the daily page are a grid of dots as opposed to lines | 
...

I was not able to figure out what ampm means, or the difference between dailycal

**Comment by dynobo** [comment]
Wrong repo, I guess? If this is related to NoTeTo and I just didn't get it, feel free to reopen!

**Comment by Bootstrap360** [comment]
Yes, wrong repo. Apologies.
